INSERT INTO cicle
VALUES ("HB","Higene BocoDental");

INSERT INTO modul 
VALUES 
("M1","HB","RECEPCIÓ I LOGÍSTICA DE LA CLINICA DENTAL"), 
("M2","HB","ESTUDI DE LA CAVITAT ORAL"), 
("M3","HB","EXPLORACIÓ DE LA CAVITAT ORAL"), 
("M4","HB","INTERVENCIÓ BUCODENTAL"), 
("M5","HB","EPIDEMIOLOGIA"), 
("M6","HB","EDUCACIÓ PER LA SALUT"), 
("M7","HB","CONSERVADORA, PERIODÒNCIA, CIRURGIA I IMPLANTS"), 
("M8","HB","PRÒTESI I ORTODÒNCIA"), 
("M9","HB"," "), 
("M10","HB","FISIOPATOLOGIA GENERAL");




